### ISSUE TITLE
When focused there is a square box around the view

### ISSUE THREAD

**Issue by EmmanuelMess** [tom5079/FloatingSearchView#2]
![photo_2022-03-27_18-03-08](https://user-images.githubusercontent.com/10991116/160300911-08c82218-4a45-423c-afad-7a7683e08627.jpg)

**Comment by tom5079** [comment]
Can you provide a reproducibple code? Thank you.

**Comment by tom5079** [comment]
Can you just provide a Layout Inspector snapshot? Thanks.

**Comment by tom5079** [comment]
Nevermind, that's the shroud that dims the background.

<img src="https://user-images.githubusercontent.com/7948651/160306114-8942d080-84f0-4fc1-b07f-a60bbc499fad.png" width="250">

set `app:dimBackground="false"` to disable the effect.
