### ISSUE TITLE
Icons are white on white background 

### ISSUE THREAD

**Issue by EmmanuelMess** [tom5079/FloatingSearchView#3]
```
<xyz.quaver.floatingsearchview.FloatingSearchView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/floating_search_view"
    android:layout_margin="@dimen/search_view_margin"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    android:elevation="8dp"
    android:gravity="center_vertical"
    android:visibility="gone"
    android:clipChildren="true"
    app:searchHint="@string/search_hint"
    app:leftActionMode="showHome"
    app:close_search_on_keyboard_dismiss="true"/>
```

![photo_2022-03-27_18-03-08](https://user-images.githubusercontent.com/10991116/160300911-08c82218-4a45-423c-afad-7a7683e08627.jpg)

**Comment by tom5079** [comment]
Can you check if the icon is actually there? Try to change the background of the search bar to dark color.

**Comment by EmmanuelMess** [comment]
> Can you check if the icon is actually there? Try to change the background of the search bar to dark color.

The same code works on the original library. showing the icons correctly

**Comment by EmmanuelMess** [comment]
The icons are there, changing the background shows it.

**Comment by tom5079** [comment]
```
<xyz.quaver.floatingsearchview.FloatingSearchView
            android:id="@+id/floating_search_view"
            android:layout_margin="5dp"
            android:layout_width="match_parent"
            android:layout_height="?attr/actionBarSize"
            android:elevation="8dp"
            android:gravity="center_vertical"
            android:clipChildren="true"
            app:searchHint="test"
            app:leftActionMode="showHome"
            app:dimBackground="false"
            app:close_search_on_keyboard_dismiss="true"/>
```

<img src="https://user-images.githubusercontent.com/7948651/160326943-c1f5df33-d002-4088-8d03-56a2eb494c1b.png" width="250"/>

works just fine on sample application. Maybe you're setting the color of the icon somewhere else?

**Comment by EmmanuelMess** [comment]
How could I have changed the icon's color? It also looks like the background follows the rest of the app's, I am not sure how this happened.

**Comment by tom5079** [comment]
I can take a look at your project if you don't mind. Can you share the repo?

**Comment by EmmanuelMess** [comment]
https://github.com/TeamAmaze/AmazeFileManager

**Comment by tom5079** [comment]
And-- which file exactly? I don't have time to scout through all the codes

**Comment by tom5079** [comment]
@EmmanuelMess https://github.com/TeamAmaze/AmazeFileManager/tree/emmanuelmess/fix/search
This one right?

**Comment by tom5079** [comment]
![image](https://user-images.githubusercontent.com/7948651/160616461-3bf2477f-3745-47a9-a5c1-f838bd9fb6ed.png)
:thinking:

**Comment by EmmanuelMess** [comment]
Its a fix proposal, it hasn't been added to the code yet, so no issues, also that is no the official repo, just my fork.

**Comment by EmmanuelMess** [comment]
> @EmmanuelMess [https://github.com/TeamAmaze/AmazeFileManager/tree/emmanuelmess/fix/search](https://github.com/TeamAmaze/AmazeFileManager/tree/emmanuelmess/fix/search?rgh-link-date=2022-03-29T12%3A38%3A33Z) This one right?

Yes

**Comment by EmmanuelMess** [comment]
Pushed a "wip" commit.

**Comment by tom5079** [comment]
The icon is using `?attr/colorControlNormal` as the tint value. Seems like you set it to white for your theme.
I'm going to add some additional attributes for styling. You can set the tint directly to view `findViewById(R.id.left_action)` for a quick fix.

**Comment by tom5079** [comment]
update to version `1.2.0-rc1`. Thank you.

**Comment by tom5079** [comment]
`1.2.0-rc2` fixed crashing when `colorSurface` is not defined. To change the card color according to the theme, define `colorSurface` in your theme or use `Theme.MaterialColors` as a parent.
