### ISSUE TITLE
suggestionsAnimDuration error

### ISSUE THREAD

**Issue by a-jahanshahlo** [tom5079/FloatingSearchView#6]
this error showed me.
 error: attribute suggestionsAnimDuration (aka xx.xx.xx:suggestionsAnimDuration) not found.

but I declared it.

**Comment by tom5079** [comment]
make sure you're using `http://schemas.android.com/apk/res-auto` namespace, aka `app`

**Comment by a-jahanshahlo** [comment]
This is my fragment view

`
<?xml version="1.0" encoding="utf-8"?>
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"

    tools:context=".activities.TravelFragment">
`


and this is my searchview

`
 <xyz.quaver.floatingsearchview.FloatingSearchView
        android:id="@+id/floating_search_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:searchBarMarginLeft="@dimen/margin_2"
        app:searchBarMarginTop="@dimen/margin_2"
        app:searchBarMarginRight="@dimen/margin_2"
        app:searchHint="Search..."
        app:suggestionsAnimDuration="250"
        app:showSearchKey="false"
        app:leftActionMode="showHamburger"
app:suggestionAnimDuration="250"
        app:elevation="4dp"
        app:close_search_on_keyboard_dismiss="true"
        />
`

**Comment by tom5079** [comment]
oh there is a typo in the document
It's `suggestionAnimDuration`.
